title: Aaron Carson
email: hello@aaroncarson.co.uk
author: Aaron Carson
url: "https://aaroncarson.co.uk"
twitter_username: acar321
github_username: caraar12345

host: 0.0.0.0

# Build settings
permalink: :title/
sass:
  sass_dir: assets/css/

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
